language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo add-apt-repository --yes ppa:beineri/opt-qt541
  - sudo apt-get update -qq
  - if [[ $CC == gcc ]]; then
      sudo apt-get install gcc-4.8 g++-4.8;
    fi
  - sudo apt-get install cmake libboost-python-dev libcups2-dev libhunspell-dev
    libhyphen-dev liblcms2-dev libpodofo-dev libtiff-dev libxml2-dev
    python-all-dev zlib1g-dev qt54base qt54declarative qt54webkit qt54tools
    libgraphicsmagick++1-dev libopenscenegraph-dev libpoppler-dev
    libpoppler-private-dev libwpg-dev libvisio-dev libicu-dev
  # OpenSceneGraph 3.0.1-3. Remove if new version is available on Travis.
  - sudo sed -i '244s/ ptrOld/ (void *)ptrOld/' /usr/include/OpenThreads/Atomic

script:
  - source /opt/qt54/bin/qt54-env.sh
  - if [[ $CC == gcc ]]; then
      export CC="gcc-4.8";
      export CXX="g++-4.8";
      export NPROC=8;
    else
      export NPROC=1;
    fi

  - cmake .
  - make -j$NPROC

notifications:
  email: false
